### ISSUE TITLE
Use .netrc for user/password

### ISSUE THREAD

**Issue by LukeHoersten** [theanalyst/ix.el#3]
I'd prefer to use the `.netrc` just as the CLI version of `ix` does. Any chance this could be used?

**Comment by theanalyst** [comment]
Hmm shouldn't be difficult to configure, I'll try

**Comment by theanalyst** [comment]
This can be done by the following snippet..
```elisp
(setq netrc-credentials "~/.netrc")
(let* 
     ((auth-credentials (netrc-parse netrc-credentials)) 
      (ixentry (netrc-machine auth-credentials "http://ix.io"))) 
         (when ixentry 
             (setq ix-user (netrc-get ixentry "login"))
             (setq ix-token (netrc-get ixentry "password"))))
```

**Comment by theanalyst** [comment]
I guess I can add this in the readme.. to add the following snippet to `.emacs` when you need to use netrc credentials

**Comment by LukeHoersten** [comment]
Thanks!
